// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package users

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetUser(ctx context.Context, name string) (IntegratingTestsUser, error)
	GetUsers(ctx context.Context) ([]IntegratingTestsUser, error)
	PersistUser(ctx context.Context, name string) (sql.Result, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
